name = "ClusterRunner"
uuid = "3325b298-19c5-4432-bbc2-e7898443f212"
authors = ["Ryan Humble <rahumble@yahoo.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CSV = "0.5"
DataFrames = "0.20"
DataStructures = "0.17"
